// Code generated by "stringer -type=ErrorType"; DO NOT EDIT.

package scrapers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[NoResultFoundError-1]
	_ = x[IsinMismatchError-2]
	_ = x[GetSearchError-3]
	_ = x[ParseSearchError-4]
	_ = x[GetInfoError-5]
	_ = x[ParseInfoError-6]
	_ = x[PriceNotFoundError-7]
	_ = x[InvalidPriceError-8]
	_ = x[DateNotFoundError-9]
	_ = x[InvalidDateError-10]
	_ = x[IsinNotFoundError-11]
}

const _ErrorType_name = "SuccessNoResultFoundErrorIsinMismatchErrorGetSearchErrorParseSearchErrorGetInfoErrorParseInfoErrorPriceNotFoundErrorInvalidPriceErrorDateNotFoundErrorInvalidDateErrorIsinNotFoundError"

var _ErrorType_index = [...]uint8{0, 7, 25, 42, 56, 72, 84, 98, 116, 133, 150, 166, 183}

func (i ErrorType) String() string {
	if i < 0 || i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
