name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Download test data
      run: wget -np -r -nH --cut-dirs=4 https://github.com/mmbros/quotes/raw/main/test/internal/quotescraper.zip

    - name: Test
      run: go test -v ./...
